steps:

   - id: 'Rodando docker-compose'
     name: 'gcr.io/$PROJECT_ID/docker-compose:1.24.0'
     args: ['-f','docker-compose.yaml','up','-d']
     
   - id: "Rodando composer"
     name: 'gcr.io/cloud-builders/docker'
     args: ['exec','-t','app','composer','install']
     
   - id: "Copiando .env"
     name: 'gcr.io/cloud-builders/docker'
     args: ['exec','-t','app','cp','.env.example','.env']
     
   - id: "Rodando key:generate"
     name: 'gcr.io/cloud-builders/docker'
     args: ['exec','-t','app','php','/var/www/artisan','key:generate'] 
     
   - id: "Rodando migrations"
     name: 'gcr.io/cloud-builders/docker'
     args: ['exec','-t','app','php','/var/www/artisan','migrate'] 
     
   - id: "Rodando pestPHP"
     name: 'gcr.io/cloud-builders/docker'
     args: ['exec','-t','app','php','./vendor/bin/pest']