version: '3'

services:
  app:
    build: .
    container_name: pp-simplificado-app
    volumes:
        - .:/var/www
    networks:
        - app-network
    depends_on:
        - db
  nginx:
    build: .docker/nginx
    container_name: pp-simplificado-nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
    networks:
      - app-network
  db:
    build: ./.docker/mysql
    container_name: pp-simplificado-db
    restart: always
    tty: true
    ports:
        - "3306:3306"
    volumes:
        - ./.docker/dbdata:/var/lib/mysql
        - ./.docker/mysql:/docker-entrypoint-initdb.d
    environment:
        - MYSQL_DATABASE=pp_simplificado
        - MYSQL_ROOT_PASSWORD=root
    networks:
        - app-network
networks:
  app-network:
    driver: bridge